"""added uniqueness restriction on period and apartment_id columns

Revision ID: bb1ac0b4d2ed
Revises: 50cd0a428498
Create Date: 2024-06-07 19:18:08.507325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1ac0b4d2ed'
down_revision: Union[str, None] = '50cd0a428498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_period_apartment_uc', 'rent_payment', ['period', 'apartment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_period_apartment_uc', 'rent_payment', type_='unique')
    # ### end Alembic commands ###
